### ISSUE TITLE
현재 아쉬운점/약간의버그점? 등등 올려봅니다.

### ISSUE THREAD

**Issue by jeyun0** [mu29/danbi#1]
# 추가요청
- 인벤토리 꽉 찼을경우 아이템을 얻으려고 할때 알림 뜨는거 예) '인벤토리가 꽉찼습니다.'
- 길드UI에 기능이 더 많이 생겼으면 좋겠네요. (길드UI에 길드이름이 안뜨는거 부터해서 여러가지 많이 부족한듯 보임.)
# 수정요청
- 길드를 가입 및 생성했음에도 닉네임 위의 '길드 없음' 표시가 바뀌지 않음.
# 아쉬운점
- 단축키 + 스킬 완성안된거.
- 아이템 떨구기가 완성 안된건가..?
# 그외에?
- 아이템은 왼쪽마우스 클릭하면 선택되서 옮겨지는데 무기는 왼쪽마우스 클릭해도 선택이 안됨.

킁. 피드백 자주 남길게요.

**Comment by mu29** [comment]
### Accept
- 아직 관련 시스템 경고 메시지가 하나도 구현되어있지 않습니다 ㅠㅠ
- 길드 UI도 개편하도록 하겠습니다.
- 단축키 기능이 없었군요.

### Decline
- 아이템 드랍은 선택 후 필드에 올리면 됩니다.
- 무기가 옮겨지지 않는 것처럼 보이는 것은 마우스 아이콘과 이미지가 같기 때문입니다.
