### ISSUE TITLE
단비의 문제는 아니고 깃허브가  설치 안 되네요.

### ISSUE THREAD

**Issue by whdtjd5294** [mu29/danbi#10]
그때문에 단비 설치를 아예 할 수가 없는데.
유효성 검사를 할 수 없다면서 설치가 80% 쯤에서 꺼집니다..

플랫폼 버전 정보
    Windows             : 10.0.10586.0 (Win32NT)
    Common Language Runtime     : 4.0.30319.42000
    System.Deployment.dll       : 4.6.1078.0 built by: NETFXREL3STAGE
    clr.dll             : 4.6.1080.0 built by: NETFXREL3STAGE
    dfdll.dll           : 4.6.1038.0 built by: NETFXREL2
    dfshim.dll          : 10.0.10586.0 (th2_release.151029-1700)

원본
    배포 url          : http://github-windows.s3.amazonaws.com/GitHub.application
                        서버      : AmazonS3
    응용 프로그램 url         : http://github-windows.s3.amazonaws.com/Application%20Files/GitHub_3_2_0_0/GitHub.exe.manifest
                        서버      : AmazonS3

ID
    배포 ID       : GitHub.application, Version=3.2.0.0, Culture=neutral, PublicKeyToken=317444273a93ac29, processorArchitecture=x86
    응용 프로그램 ID      : GitHub.exe, Version=3.2.0.0, Culture=neutral, PublicKeyToken=317444273a93ac29, processorArchitecture=x86, type=win32

응용 프로그램 요약
    \* 설치 가능한 응용 프로그램입니다.
    \* 트러스트 url 매개 변수가 설정되었습니다.
오류 요약
    다음은 오류에 대한 요약입니다. 이러한 오류의 세부 정보는 나중에 로그에 기록됩니다.
    \* http://github-windows.s3.amazonaws.com/GitHub.application 활성화로 예외가 발생했습니다. 다음 실패 메시지가 발견되었습니다.
        + libcef.dll 파일에 매니페스트에 지정된 것과 다른 계산된 해시가 있습니다.

구성 요소 저장소 트랜잭션 실패 요약
    트랜잭션 오류가 발생하지 않았습니다.

경고
    이 작업을 수행하는 동안 경고가 발생하지 않았습니다.

작업 진행 상태
    \* [2016-09-04 오후 2:01:01]: http://github-windows.s3.amazonaws.com/GitHub.application 활성화가 시작되었습니다.
    \* [2016-09-04 오후 2:01:02]: 배포 매니페스트의 처리가 완료되었습니다.
    \* [2016-09-04 오후 2:01:02]: 응용 프로그램 설치가 시작되었습니다.
    \* [2016-09-04 오후 2:01:03]: 응용 프로그램 매니페스트 처리가 완료되었습니다.
    \* [2016-09-04 오후 2:01:49]: 호환 가능한 런타임 버전 4.0.30319을(를) 찾았습니다.
    \* [2016-09-04 오후 2:01:49]: 트러스트 요청과 플랫폼 검색이 완료되었습니다.

오류 정보
    이 작업을 수행하는 동안 다음 오류가 발생했습니다.
    \* [2016-09-04 오후 2:03:17] System.Deployment.Application.InvalidDeploymentException(HashValidation)
        - libcef.dll 파일에 매니페스트에 지정된 것과 다른 계산된 해시가 있습니다.
        - 원본: System.Deployment
        - 스택 추적:
            위치: System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
            위치: System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
            위치: System.Deployment.Application.ComponentVerifier.VerifyComponents()
            위치: System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
            위치: System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
            위치: System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
            위치: System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
            위치: System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

구성 요소 저장소 트랜잭션 정보
    트랜잭션 정보를 사용할 수 없습니다.

**Comment by whdtjd5294** [comment]
해결했습니다. 무시하고 그냥 진행하면 되네요 !

**Comment by h4wldev** [comment]
해결하신듯 하니 이슈 닫겠습니다.
