### ISSUE TITLE
ClientRGSS3가 데이터 읽기 실패라며 열리지 않아요.

### ISSUE THREAD

**Issue by indizs** [mu29/danbi#12]
오랜만에 개발하려고 다운받아서 키는데 ClientRGSS3가 열리지 않네요..
그냥 Client 잘 열리긴 하는데.. rgss3가 빨라서 rgss3 쓰고 싶습니다 ㅠㅠ

파일 확인 부탁드려요..

**Comment by jubin-park** [comment]
Game.rxproj을 메모장으로 실행한 뒤, RPGXP **1.05**을 현재 사용하고 있는 버전으로 수정하십시오.
**1.05**는 Steam 버전, **1.03**은 비정품 한글판 버전입니다.

**Comment by indizs** [comment]
정품으로 켜도 테스트 플레이하면 RGSS 코어 라이브러리 ~~ 라고 에러 떴는데, 인터넷좀 하다보니깐 갑자기 되네요. 감사합니다
