### ISSUE TITLE
npc 기능 문의

### ISSUE THREAD

**Issue by indizs** [mu29/danbi#13]
서버 NpcFunction 에서 npc.turnright(); 이렇게 해도 움직이질 않네요..
ctx.writeandflush(packet.moveCharacter(n,n,n,n,n,n) 이렇게 하고 클라이언트 조금 수정하니깐 움직이긴 하는데 좀 뻣뻣하게 움직이고.. 자연스럽게 그냥 걷듯이 움직이는 방법은 없을까요?
그리고 제 방식대로 하면 npc 위치 공유가 안될꺼같은데..

npc 사용방법이 궁금합니다.ㅠ

**Comment by mu29** [comment]
`Character#turnRight` 함수는 오른쪽을 바라보는 함수이고, 오른쪽으로 이동하시려면 `Character#moveRight` 를 사용하시면 됩니다.

**Comment by indizs** [comment]
서버 npc부분에 characterType = Type.Character.NPC; 이 없었고
클라 npc 부분
attr_accessor :finalX
 attr_accessor :finalY

패킷부분
npc = Game.map.getNPC(recv["no"])
        return if not npc
        case recv["d"]
        when 2
          npc.move_down
        when 4
          npc.move_left
        when 6
          npc.move_right
        when 8
          npc.move_up
        end
        npc.finalX = recv["x"]
        npc.finalY = recv["y"]

이빠져있었네요. 감사합니다!!

**Comment by mu29** [comment]
앗 ㅎㅎ 혹시 수정해서 PR 날려주실 수 있나요?

**Comment by indizs** [comment]
넵! 이참에 PR 날리는법도 배워야겠네요..

**Comment by mu29** [comment]
감사합니다 :)

**Comment by indizs** [comment]
뮤님 commit to master 만 하면 되는건가요? 코밋은 보냈는데.. pull request를 해야하나요?

**Comment by mu29** [comment]
마스터 브랜치에 push 하신다음 https://github.com/indizs/danbi 들어가셔서 new pull request 누르시면 돼요.
