### ISSUE TITLE
서버실행시키자 오류가 뜹니다.

### ISSUE THREAD

**Issue by happyhg3927** [mu29/danbi#15]
ㅠㅠ
어떻게 해결해야 할까요.

E:\danbi-master\Server\src\game\User.java
Error:(3, 24) java: package io.netty.channel does not exist
Error:(17, 17) java: cannot find symbol
  symbol:   class ChannelHandlerContext
  location: class game.User
Error:(58, 34) java: cannot find symbol
  symbol:   class ChannelHandlerContext
  location: class game.User
Error:(61, 35) java: cannot find symbol
  symbol:   class ChannelHandlerContext
  location: class game.User
Error:(69, 32) java: cannot find symbol
  symbol:   class ChannelHandlerContext
  location: class game.User
Error:(84, 33) java: cannot find symbol
  symbol:   class ChannelHandlerContext
  location: class game.User
Error:(88, 38) java: cannot find symbol
  symbol:   class ChannelHandlerContext
  location: class game.User
Error:(97, 21) java: cannot find symbol
  symbol:   class ChannelHandlerContext
  location: class game.User
Error:(135, 16) java: cannot find symbol
  symbol:   class ChannelHandlerContext
  location: class game.User
E:\danbi-master\Server\src\packet\JsonEncoder.java
Error:(3, 23) java: package io.netty.buffer does not exist
Error:(4, 23) java: package io.netty.buffer does not exist
Error:(5, 24) java: package io.netty.channel does not exist
Error:(6, 30) java: package io.netty.handler.codec does not exist
Error:(7, 30) java: package io.netty.handler.codec does not exist
Error:(8, 21) java: package io.netty.util does not exist
Error:(13, 34) java: package com.fasterxml.jackson.core does not exist
Error:(14, 38) java: package com.fasterxml.jackson.databind does not exist
Error:(15, 38) java: package com.fasterxml.jackson.databind does not exist
Error:(18, 34) java: cannot find symbol
  symbol: class MessageToMessageEncoder
Error:(21, 31) java: cannot find symbol
  symbol:   class ChannelHandlerContext
  location: class packet.JsonEncoder
Error:(32, 49) java: cannot find symbol
  symbol:   class CorruptedFrameException
  location: class packet.JsonEncoder
E:\danbi-master\Server\src\network\Initializer.java
Error:(2, 24) java: package io.netty.channel does not exist
Error:(3, 24) java: package io.netty.channel does not exist
Error:(4, 31) java: package io.netty.channel.socket does not exist
Error:(5, 30) java: package io.netty.handler.codec does not exist
Error:(6, 30) java: package io.netty.handler.codec does not exist
Error:(11, 34) java: cannot find symbol
  symbol: class ChannelInitializer
Error:(11, 53) java: cannot find symbol
  symbol: class SocketChannel
Error:(14, 36) java: cannot find symbol
  symbol:   class SocketChannel
  location: class network.Initializer
E:\danbi-master\Server\src\packet\Packet.java
Error:(9, 23) java: package org.json.simple does not exist
Error:(17, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(25, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(70, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(78, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(101, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(110, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(122, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(134, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(144, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(155, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(165, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(176, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(187, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(198, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(209, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(217, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(225, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(233, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(244, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(258, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(268, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(276, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(287, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(301, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(317, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(326, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(353, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(378, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(388, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(398, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(406, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(414, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(438, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(447, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(456, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(464, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(472, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(482, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(489, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(497, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(506, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(514, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(523, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(537, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(545, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(553, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(561, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(570, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(584, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(598, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(606, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(615, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
Error:(626, 23) java: cannot find symbol
  symbol:   class JSONObject
  location: class packet.Packet
E:\danbi-master\Server\src\game\Field.java
Error:(5, 23) java: package org.json.simple does not exist
Error:(291, 27) java: cannot find symbol
  symbol:   class JSONObject
  location: class game.Field
Error:(297, 39) java: cannot find symbol
  symbol:   class JSONObject
  location: class game.Field
E:\danbi-master\Server\src\network\Handler.java
Error:(5, 24) java: package io.netty.channel does not exist
Error:(6, 24) java: package io.netty.channel does not exist
Error:(12, 23) java: package org.json.simple does not exist
Error:(19, 36) java: cannot find symbol
  symbol: class ChannelInboundHandlerAdapter
Error:(24, 34) java: cannot find symbol
  symbol:   class ChannelHandlerContext
  location: class network.Handler
Error:(149, 24) java: cannot find symbol
  symbol:   class ChannelHandlerContext
  location: class network.Handler
Error:(149, 51) java: cannot find symbol
  symbol:   class JSONObject
  location: class network.Handler
Error:(194, 27) java: cannot find symbol
  symbol:   class ChannelHandlerContext
  location: class network.Handler
Error:(194, 54) java: cannot find symbol
  symbol:   class JSONObject
  location: class network.Handler
Error:(245, 40) java: cannot find symbol
  symbol:   class ChannelHandlerContext
  location: class network.Handler
Error:(250, 42) java: cannot find symbol
  symbol:   class ChannelHandlerContext
  location: class network.Handler
Error:(256, 33) java: cannot find symbol
  symbol:   class ChannelHandlerContext
  location: class network.Handler
E:\danbi-master\Server\src\network\Server.java
Error:(2, 26) java: package io.netty.bootstrap does not exist
Error:(3, 24) java: package io.netty.channel does not exist

**Comment by mu29** [comment]
https://github.com/mu29/danbi/wiki/1.-단비-서버-준비와-세팅#1-4-깃허브-github

여기 맨 아래 라이브러리 세팅하는 부분 확인해주세요.

**Comment by happyhg3927** [comment]
제가 제대로 읽어보지도 않고 질문을 했네요. 친절한 답변 감사합니다. 해결 되었습니다.
