### ISSUE TITLE
여기에 질문 드려도 되나요?

### ISSUE THREAD

**Issue by moistee** [mu29/danbi#16]
![image](https://cloud.githubusercontent.com/assets/24874632/21631552/d1efacd4-d27f-11e6-8c05-04ee2331fd86.png)

IDEA로 파일 수정을 하려고 하는데, 파일 왼쪽에 있는 그림처럼 전부 락이 걸려있네요

수정하려고 하면 File is not writable 이라고 뜨면서 수정이 안됩니다.

혹시나해서 읽기전용으로 되어있는지 찾아봤지만 그것도 아니네요.

대체 문제가 뭘까요 ㅠ ㅠ

**Comment by mu29** [comment]
`src/*` 의 내용을 수정하시면 됩니다!

**Comment by moistee** [comment]
헉.. 엄청나게 빠른 답변 감사합니다 :3 

죄송합니다만.. 어디서 수정 할 수 있는건가요? 염치없지만 힌트좀 부탁드리겠습니다

**Comment by mu29** [comment]
![d1efacd4-d27f-11e6-8c05-04ee2331fd86](https://cloud.githubusercontent.com/assets/8934513/21631614/9db070b0-d280-11e6-8712-23ba0749f7b9.png)

보시면 지금 `bin` 폴더 안의 `.class` 파일을 수정하려 하시는데, `bin` 폴더를 접으시면 그 아래쯤 `src` 폴더가 보이실 거에요. 그 안의 `.java` 파일을 수정하시면 됩니다. 

<img width="250" alt="2017-01-04 1 22 22" src="https://cloud.githubusercontent.com/assets/8934513/21631635/d8ec03b0-d280-11e6-873e-f3bf571d9137.png">

**Comment by moistee** [comment]
헉.. 제대로 찾아보지도 않고 바보짓 하고 있었네요 ㅋㅋㅋㅋㅋㅋ 이렇게 간단한 문제일줄이야
너무 감사합니다 :3

**Comment by mu29** [comment]
ㅎㅎ 급하다 보면 실수할수도 있죠. 즐거운 개발 하시길 바랍니다!
