### ISSUE TITLE
아이템 수정과 생성에 대해서 질문!

### ISSUE THREAD

**Issue by moistee** [mu29/danbi#17]
![image](https://cloud.githubusercontent.com/assets/24874632/21647691/a0d6092c-d2de-11e6-95e7-3a197c6f0e73.png)

저렇게 나비캣에서 아이템을 만들고

![image](https://cloud.githubusercontent.com/assets/24874632/21647711/b8f76dd4-d2de-11e6-9b1b-6e2ff0968335.png)

게임 내에서 아이템을 얻은 후에 인벤토리를 열면 저렇게 에러가 떠요!
목도랑 똑같은 이미지를 넣어도 새로만든 아이템이면 무조건 튕기는데 왜 그런걸까요!?

![image](https://cloud.githubusercontent.com/assets/24874632/21647765/e4d9c60e-d2de-11e6-9b28-aa4a97928efa.png)

그리고 무기의 능력치를 변경해보았는데 아무리 리프레쉬해도 게임상에서 적용이 안되더라구요
혹시 맵을 적용하는 것처럼 클라이언트나 서버에 따로 저장을 해줘야하는 것이 있나요?

**Comment by moistee** [comment]
닫힌 이슈를 보니까 데이터매니저를 사용하면 되는건가 보네요!

**Comment by moistee** [comment]
![image](https://cloud.githubusercontent.com/assets/24874632/21664829/60db2700-d32c-11e6-8d6f-a08245acb997.png)

데이터매니저도 서버처럼 똑같이 IDEA로 실행하면 되는건가요?
실행해봤더니 데이터베이스에 연결합니다에서 멈추네요 8ㅅ8

**Comment by mu29** [comment]
External Libraries 에 `Library/MySQL/mysql-connector-java-5.1.33-bin` 을 추가해주세요.

**Comment by moistee** [comment]
![image](https://cloud.githubusercontent.com/assets/24874632/21667871/ecdbde08-d33f-11e6-80f2-7121dcdd0c4b.png)

감사합니다! 덕분에 데이터베이스 연결까지는 성공했습니다.
근데 그 뒤로는 무반응입니다 ㅠ ㅠ
여기에서 어떻게 아이템 데이터를 추출하는건가요?

**Comment by mu29** [comment]
0을 치면 아이템 데이터가, 1을 치면 스킬 데이터가 추출됩니다.
생성된 파일을 `Client/GameData` 폴더에 넣으시면 됩니다.

**Comment by moistee** [comment]
0을 입력했더니 오류코드가 나오네요 쥬르륵 8ㅅ8
친절하게 알려주셔서 감사합니다 ㅠㅅㅠ

![image](https://cloud.githubusercontent.com/assets/24874632/21667964/be24347e-d340-11e6-841f-1f626b56952e.png)

**Comment by mu29** [comment]
`DataManager.java` 28행의 ```rs = statement.executeQuery("SELECT * FROM `item`");``` 을 ```rs = statement.executeQuery("SELECT * FROM `setting_item`");``` 으로 바꿔주세요!

**Comment by moistee** [comment]
아하 setting_item으로 바뀌어있지않아서 그랬던거군요!
거듭 감사드립니다 헤헷 (__)

**Comment by mu29** [comment]
제 실순데요 뭐 ㅋㅋ
이슈 닫겠습니다!
