### ISSUE TITLE
새로운 SQL 항목 읽어오기 실패

### ISSUE THREAD

**Issue by moistee** [mu29/danbi#18]
안녕하세요!
강화 기능을 추가하고 싶어서 만지작거리는데
SQL 항목을 추가시키고 로드했을때 설정값이 있으면 튕깁니다 8ㅅ8

![image](https://cloud.githubusercontent.com/assets/24874632/21739410/bc68b65c-d4dd-11e6-800f-d10e07b3b2d6.png)

![image](https://cloud.githubusercontent.com/assets/24874632/21739413/ccccede2-d4dd-11e6-8997-6f40437ffa51.png)

![image](https://cloud.githubusercontent.com/assets/24874632/21739418/dd634b2e-d4dd-11e6-99e5-a46dc09f61dc.png)

![image](https://cloud.githubusercontent.com/assets/24874632/21739420/e4f9cb74-d4dd-11e6-9a7c-6fb6b50fe259.png)

![image](https://cloud.githubusercontent.com/assets/24874632/21739423/ee3c05f8-d4dd-11e6-88f4-790ee0663f4c.png)

![image](https://cloud.githubusercontent.com/assets/24874632/21739425/0af4d6ac-d4de-11e6-862c-a0e844747b2f.png)

![image](https://cloud.githubusercontent.com/assets/24874632/21739432/37d6d350-d4de-11e6-8f0d-d900858ad34c.png)

![image](https://cloud.githubusercontent.com/assets/24874632/21739438/53afed82-d4de-11e6-90d1-1de0469a0c69.png)

셋팅은 일단 이렇게 되어있는데
SQL에 이렇게 null값만 있으면 튕기지 않지만

![image](https://cloud.githubusercontent.com/assets/24874632/21739466/f39941b8-d4de-11e6-9e9f-d936f531187e.png)

![image](https://cloud.githubusercontent.com/assets/24874632/21739428/1d1c44a0-d4de-11e6-984b-0c407c05e43c.png)

SQL 테이블에 값을 주게되면 이렇게 셋팅파일 로드중에 튕기게 됩니다 8ㅅ8
밤새 머리싸매고 고민해봤는데 도저히 답을 모르겠어서 염치불구하고 질문을 드려봅니다 ㅠ ㅠ

**Comment by mu29** [comment]
해당 테이블 구조를 보니 no 라는 컬럼이 없네요. 다른 테이블 참고하여 생성해보세요.

**Comment by moistee** [comment]
헉.. 감사합니다
정말 no가 없는 테이블은 없네요
매번 이렇게 어처구니없는 실수를 하고 질문을 올리네요 ㅋㅋㅋㅋㅋㅋ 창피합니다

답변 정말 감사합니다 >ㅅ<
