### ISSUE TITLE
자바 코딩 관련 질문!

### ISSUE THREAD

**Issue by moistee** [mu29/danbi#19]
안녕하세요! 어김없이 찾아온 질문돌이입니다!
요즘 자바 공부하면서 나름 만들어본답시고 강화 코딩을 해보고 있는데
다른 클래스에서 메소드를 불러오는 과정에서 막혔습니다
번거로우실까봐 되도록이면 질문 안드리려고 끙끙거려봤는데 도움이 너무나 간절합니다 .. 크흡 ㅠ ㅠ
힌트라도 알려주신다면 정말 감사하겠습니다 굽신...

User
![image](https://cloud.githubusercontent.com/assets/24874632/21792736/29b2ff3a-d72f-11e6-8b65-54a1b612858a.png)

![image](https://cloud.githubusercontent.com/assets/24874632/21792767/637f8878-d72f-11e6-9a95-2d676b1c379f.png)

GameData
![image](https://cloud.githubusercontent.com/assets/24874632/21792804/a57f57a8-d72f-11e6-917e-232d0ea141c0.png)

GameData에 Strengthen 이라는 클래스를 만들어서 SQL에서 강화확률, 필요한 강화석 갯수를
받아온다음 
User에 있는 강화 메소드 stonefind에 연결시키려고 Strengthen strdata = new Strengthen(); 를 넣어봤는데
괄호안에 ResultSet이 꼭 들어가야하는건지 오류가 뜹니다(...)
방법이 있을까요? 뮤 선생님 !!!

**Comment by mu29** [comment]
네, 저기서는 꼭 필요합니다.
`Strengthen` 클래스를 강화 정보 저장용으로 만드실 예정이라면, `Item`, `Skill` 이 어떻게 구현되어 있는지 참고해보세요.
아마 서버가 켜질 때 정보를 한번 로드해서 사용할 겁니다.

**Comment by moistee** [comment]
감사합니다!
근데 ResultSet을 넣으면 아래와 같은 문구가 뜨는데 무슨 뜻일까요?

![image](https://cloud.githubusercontent.com/assets/24874632/21792979/e2e0e07a-d730-11e6-8c77-afaae9a30149.png)

**Comment by mu29** [comment]
`ResultSet` 객체를 넣으셔야 합니다.
`GameData.loadSettings` 함수 참고해보시겠어요?

**Comment by moistee** [comment]
![image](https://cloud.githubusercontent.com/assets/24874632/21796844/b945c140-d74e-11e6-885c-ad1ba8bccb41.png)

![image](https://cloud.githubusercontent.com/assets/24874632/21796868/de709dc8-d74e-11e6-85c2-29233589568d.png)

힝 도저히 모르겠어요.. loadSettings에 항목은 등록시켜놓고 파일도 잘 읽어오는데
그래도 위에랑 똑같은 문구가 뜨네요. 
User에 있는 Strengthen이랑 어떻게 연결시켜야하는지 감이 안잡힙니당 ㅠㅠ

**Comment by mu29** [comment]
저렇게 사용하지 마시고, 다른 코드에서 `GameData` 를 어떻게 쓰나 살펴보세요.
ex) `User#getStr`
