### ISSUE TITLE
danbiRGSS3 MUI::Register Error

### ISSUE THREAD

**Issue by deran2016** [mu29/danbi#21]
---------------------------
DanbiClient
---------------------------
Script '    MUI :: Register' line 111: NoMethodError occurred.

undefined method `width' for nil:NilClass
---------------------------
확인   
---------------------------

회원가입을 누를시 발생하는 에러입니다.

**Comment by mu29** [comment]
111행 근처에 코드도 같이 올려주실 수 있나요?
