### ISSUE TITLE
danbi

### ISSUE THREAD

**Issue by norhu1130** [mu29/danbi#23]
저는 danbi로 모든걸준비 세팅을끝냈습니다
하지만 오류란것이있었습니다
RPGXP로 프로젝트불러오기에실패한것이죠....어떻게해아할까요

**Comment by mu29** [comment]
정확하진 않지만 RPGXP 프로젝트 파일(*.rxproj?)을 메모장으로 열어 버전을 사용하시는 RPGXP 툴의 버전으로 바꾸면 되는 것으로 기억합니다.

**Comment by norhu1130** [comment]
1.0.2여서 1.0.2로바꿔도
Failed to load actor data
1.0.5설치하고 1.0.5로바꿔도 Failed to load actor data 가나네요

**Comment by norhu1130** [comment]
아 해결됬습니다
