### ISSUE TITLE
정의되지 않은 메소드 : image

### ISSUE THREAD

**Issue by Soedam** [mu29/danbi#4]
---
## DanbiClient

スクリプト '    MUI :: ItemInfo' の 30 行目で NoMethodError が?生しました。
## 확인   

해당 오류를 복사했습니다.

스킬이 2개 이상, 상점에 아이템이 2개 이상일 때 스킬, 상점 UI를 띄우면 해당 오류가 뜨며 종료됩니다. UI 관련 스크립트는 건들지 않았습니다.

**Comment by mu29** [comment]
데이터베이스에 아이템을 생성한 다음 DataManager를 실행하여 item.txt를 만들고, 이걸 GameData 폴더에 넣어주셔야 합니다.

**Comment by Soedam** [comment]
감사합니다.
