### ISSUE TITLE
Mysql 한글 깨짐

### ISSUE THREAD

**Issue by indizs** [mu29/danbi#6]
유저 닉네임을 한글로하면 나비켓에서는 ???로 생성되는 한글깨짐오류가 있네요..
메뉴얼대로 eurkr 해보고 utf도 해보고 다 해봐도 깨지는데 해결하셨나요??

**Comment by h4wldev** [comment]
단비의 데이터베이스 인코딩(charset)은 utf8입니다. 데이터베이스를 생성하실때 인코딩을 utf8, utf8_general_ci 로 설정하셨는지 확인해주세요.

**Comment by indizs** [comment]
@h4wldev 감사합니다
