### ISSUE TITLE
단비이벤트생성어떻게하죠?

### ISSUE THREAD

**Issue by dnlstmffj** [mu29/danbi#9]
오늘은 단비에대해서 또 질문합니다.

1.단비에서 이벤트는 어떻게 만드나요 ? [인터프리터가 없는걸로 알고있습니다만...]

2.단비에 인터프리터를 UNR처럼 추가해주시면 안되나요??

물론 추가는 안되도 이벤트는 어떻게 만드는지 궁금합니다 ㅠㅠ

빠른답변부탁드려요 ㅠㅠ

**Comment by h4wldev** [comment]
이벤트라 하시면 NPC를 생성하는 법을 물어보시는건가요. 방법은 [RKC](http://cafe.naver.com/xpcafe)에 투게더(indizs)님이 올리신 강의에 다 나와있습니다.
- [[단비] 6.NPC를 만들어 보자!](http://cafe.naver.com/xpcafe/157286)
- [[단비] 7. 보상과 몬스터 만들기](http://cafe.naver.com/xpcafe/157302)
